#ifndef __dlg_data_acquisition__
#define __dlg_data_acquisition__

/**
@file
Subclass of dlgDataAcquisition, which is generated by wxFormBuilder.
*/

#include "gui\gui_base.h"
#include "main/data_acquisition.h"

//// end generated include

/** Implementing dlgDataAcquisition */
class DialogDataAcquisition;

class DialogDataAcquisitionParent
{
protected:
	friend DialogDataAcquisition;
	virtual int OnDialogDataAcquisitionClose(bool success) = 0;
};

class DialogDataAcquisition : public dlgDataAcquisition
{
protected:
	void OnClose(wxCloseEvent& event);
	void OnBtnStopAcquisitionClick(wxCommandEvent& event);

	DialogDataAcquisitionParent* dataParent;

	grMain::DataAcquisition data;

	std::string statusLabel;
public:
	/** Constructor */
	DialogDataAcquisition(wxWindow* parent, DialogDataAcquisitionParent* data_parent);


	int ShowForm();
	int HideForm();
	int Process();

	int UpdateForm();

	
};

#endif // __dlg_data_acquisition__
