#ifndef __dlg_gauge_configuration__
#define __dlg_gauge_configuration__

/**
@file
Subclass of dlgGaugeConfiguration, which is generated by wxFormBuilder.
*/

#include "gui\gui_base.h"
#include "base\gauges\gauge.h"
#include <memory>

/// Forward declaration of the dialog gauge configuration class.
class DialogGaugeConfiguration;

class DialogGaugeConfigurationParent
{
protected:
	friend DialogGaugeConfiguration;
	virtual int OnDialogGaugeConfigurationClose(bool submit, const std::shared_ptr<grBase::Gauge> &new_data, int param) = 0;
};

/** Implementing dlgGaugeConfiguration */
class DialogGaugeConfiguration : public dlgGaugeConfiguration
{
	protected:
		// Handlers for dlgGaugeConfiguration events.
		void OnBtnCancelClick( wxCommandEvent& event );
		void OnBtnOKClick( wxCommandEvent& event );

		/// the calling parent.
		DialogGaugeConfigurationParent* dataParent;

		/// the gauge which is modified.
		std::shared_ptr<grBase::Gauge> data;

		grBase::GaugeType TypeFromRadioButtons() const;

	public:
		/** Constructor */
		DialogGaugeConfiguration(wxWindow* parent, DialogGaugeConfigurationParent* data_parent);

		int ShowForm(const std::shared_ptr<grBase::Gauge>& data);
		int HideForm(bool submit);
		int Process();

		/// Updates the GUI from the backend data.
		int UpdateForm();

		/// Updates the backend data from the GUI.
		int UpdateData();
};

#endif // __dlg_gauge_configuration__
